export const date =[
    {
        id:1,
        name:"Piso en venta en calle Ecuador",
        state: "Santa Pola",
        zona:"Calas de Santiago Bernabeu",
        tipo:"Apartamentos",
        space: 86,
        room: 2, 
        lavatory: 2,
        terraza:"si",
        balcon: "si",
        floor: "Planta 1ª",
        comOne:"exterior con ascensor",
        dopCom:"Garaje incluido",
        location: "Orientación sur, oeste",
        constr: 1967, 
        text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece apartamento en 1 planta con ascensor en las calas de Santiago Bernabéu (Santa Pola) a 30metros del mar. La vivienda es esquina, totalmente exterior y muy luminosa 86 metros (vivienda+garaje) construidos según catastro. Se compone de:- 1 garaje/almacén cerrado con baño completo, - 2 Dormitorios amplios, - 2 Baños completos (1 de ellos en el garaje), - Cocina independiente con salida a la terraza con vistas al mar, - 1 terraza saliendo desde el salón, - Salón comedor. Ubicado en Las Calas de Santiago Bernabéu (Santa Pola), a 5 min de todo tipo de servicios. En una de las mejores zonas de Santa Pola. A pocos kilómetros del aeropuerto, así como las ciudades de Elche y Alicante, ideal para sus vacaciones o para vivir todo el año.",
        foto: "https://cdn.glitch.global/5539ba06-aed1-42cf-9a61-66f8d214a4d8/2022-09-30.png?v=1664543913049",
        showMore: false, 
        precio:147000, },
        {
            id:2,
            name:"Piso en venta en calle ANDADOR",
            state: "Santa Pola",
            zona:"Tamarit - Playa Lissa",
            tipo:"Apartamentos",
            space: 70,
            room: 2, 
            lavatory: 1,
            terraza:"si",
            balcon: "no",
            floor: "Bajo",
            comOne:"exterior sin ascensor",
            dopCom:"Garaje incluido",
            location: "Orientación este, oeste",
            constr: "", 
            text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece Bonita vivienda en la playa de Tamarit (Santa Pola). Apartamento en planta baja con dos terrazas de aproximadamente de 15 metros cada una Urbanización cerrada con plaza de aparcamiento a 100 metros de la playa y con poquisimos gastos de comunidad. Cuenta con 2 dormitorios, armarios empotrados, salón comedor con chimenea, cocina independiente totalmente equipada con salida a la 2ª terraza, baño completo, aire acondicionado, amueblada y con aparcamiento. ideal para sus vacaciones o para vivir todo el año.",
            foto: "https://cdn.glitch.me/5539ba06-aed1-42cf-9a61-66f8d214a4d8%2F2ap1.jpg?v=1637438413717",
            showMore: false,  
        precio:138000,
     },

            {
                id:3,
                name:"Piso en venta en castellon, 10",
                state: "Santa Pola",
                zona:"Puerto",
                tipo:"Apartamentos",
                space: 72,
                room: 2, 
                lavatory: 1,
                terraza:"si",
                balcon: "no",
                floor: "Planta 6ª",
                comOne:"exterior con ascensor",
                dopCom:"Garaje incluido",
                location: "Orientación este, oeste",
                constr: 1984, 
                text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece piso en Santa Pola, junto Gran Playa y Puerto. 6º planta con 72 m2 construidos según catastro en urbanización completa con piscinas, pista de tenis, zona de aparcamiento y jardines. Dos dormitorio dobles, Salon comedor con salida a la terraza, un baño completo, cocina independiente recien puesta con apenas uso, terraza y aire acondicionado. Exterior y muy luminoso. Dos ascensores. uno de ellos ideal para personas con movilidad reducida, zona de aparcamiento cubierta. Piscinas y pista polideportiva / tenis.",
                foto: "https://cdn.glitch.me/5539ba06-aed1-42cf-9a61-66f8d214a4d8%2F3ap1.jpg?v=1637438613779",
                showMore: false, 
                precio:115000,  },

                {
                    id:4,
                    name:"Piso en venta en avenida Vicente Blasco Ibáñez",
                    state: "Santa Pola",
                    zona:"Puerto",
                    tipo:"Apartamentos",
                    space: 61,
                    room: 2, 
                    lavatory: 1,
                    terraza:"si",
                    balcon: "no",
                    floor: "Planta 3ª",
                    comOne:"exterior con ascensor",
                    dopCom:"Edificio con ascensor y portero físico",
                    location: "Orientación oeste",
                    constr: 1973, 
                    text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece Vivienda con bonitas vistas al mar a escasos metros de la playa y rodeada de todo tipo de servicios. Excelente para vivir todo el año o para pasar unas vacaciones. Se compone de: -2 habitaciones -Amplio salón - comedor- cocina -Bonita terraza con vistas al mar -1 baño completo con plato de ducha -Edificio con ascensor y portero físico -Ventiladores / amueblada -61 m construidos según catastro -Año de construcción 1973.",
                    foto: "https://cdn.glitch.global/5539ba06-aed1-42cf-9a61-66f8d214a4d8/2022-09-30%20(1).png?v=1664545009180",
                    showMore: false, 
                    precio:135000,  },
                    {
                        id:5,
                        name:"Piso en venta en avenida ronda",
                        state: "Santa Pola",
                        zona:"Tamarit - Playa Lissa",
                        tipo:"Apartamentos",
                        space: 70,
                        room: 3, 
                        lavatory: 1,
                        terraza:"si",
                        balcon: "no",
                        floor: "Planta 4ª",
                        comOne:"exterior con ascensor",
                        dopCom:"Garaje incluido",
                        location: "Orientación sur",
                        constr: 1980, 
                        text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece  bonito apartamento en cuarta planta y ultima, ubicado en la zona de la Playa Lisa (Santa Pola), 70 metros construidos según catastro. Descripción: La vivienda dispone de tres dormitorios, armarios empotrado, un baño completo, cocina semi-independiente, y salón comedor con chimenea y acceso a la terraza. Ubicada en una urbanización muy bien cuidada y con pocos gatos de comunidad, con zonas ajardinadas, zona de aparcamiento. El apartamento esta situado en una zona con servicios cerca y cerca del pueblo, por lo que también es ideal como vivienda habitual o para vacacionar. Es una gran oportunidad que no deberías dejar escapar. A pocos kilómetros del aeropuerto, así como las ciudades de Elche y Alicante.",
                        foto: "https://cdn.glitch.me/5539ba06-aed1-42cf-9a61-66f8d214a4d8%2F6ap1.jpg?v=1637438897693",
                        showMore: false,  
                        precio:127000, },
            
                        {
                            id:6,
                            name:"Piso en venta en calle CONSUETA",
                            zona:"Tamarit - Playa Lissa",
                            tipo:"Apartamentos",
                            state: "Santa Pola",
                            space: 55,
                            room: 2, 
                            lavatory: 1,
                            terraza:"si",
                            balcon: "no",
                            floor: "Planta 1ª",
                            comOne:"exterior sin ascensor",
                            dopCom:"Garaje incluido",
                            location: "Orientación oeste",
                            constr: 1991, 
                            text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece bonito apartamento en planta primera, ubicado en la zona de la playa del Tamarit, (urbanización Paraíso), 55 metros construidos según catastro. Descripción: La vivienda dispone de dos dormitorios con armarios empotrados, un baño completo, con plato de ducha, cocina semi-independiente, y salón comedor con aire acondicionado, y acceso a la terraza. Ubicada en una urbanización muy bien cuidada y con pocos gatos de comunidad, con parque de juegos infantil, zona de aparcamiento, piscina comunitaria y pista de tenis. El apartamento esta situado en una zona con servicios cerca y a pasos del pueblo, por lo que también es ideal como vivienda habitual o para vacacionar..",
                            foto: "https://cdn.glitch.global/5539ba06-aed1-42cf-9a61-66f8d214a4d8/2022-10-04.png?v=1664877524750",
                            showMore: false,  
                            precio:90000, },
                            {
                                id:7,
                                name:"Piso en venta en calle venezuela",
                                zona:"Calas de Santiago Bernabeu",
                                tipo:"Apartamentos",
                                state: "Santa Pola",
                                space: 102,
                                room: 4, 
                                lavatory: 2,
                                terraza:"si",
                                balcon: "si",
                                floor: "Planta 4ª",
                                comOne:"exterior sin ascensor",
                                dopCom:"Garaje - no",
                                location: "Orientación norte, oeste",
                                constr: 1965, 
                                text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece piso muy amplio haciendo esquina con vistas despejadas al mar. Es una 4 planta sin ascensor en las calas de Santiago Bernabéu (Santa Pola) a pocos metros del mar. La vivienda es esquina, totalmente exterior y muy luminosa 102 metros construidos según catastro. Se compone de: - 4 Dormitorios amplios - 2 Baños completos con plato de ducha - Cocina independiente - 1 terraza amplia con vistas al mar - Salón comedor - Comedor - Lavadero. Ubicado en Las Calas de Santiago Bernabéu (Santa Pola), a 2 min de todo tipo de servicios..",
                                foto: "https://cdn.glitch.global/5539ba06-aed1-42cf-9a61-66f8d214a4d8/2022-10-17%20(2).png?v=1666004222947",
                                showMore: false,  
                                precio:120000, },
                                {
                                    id:8,
                                    name:"Piso en venta en avenida RONDA",
                                    zona:"Tamarit - Playa Lissa",
                                    tipo:"Apartamentos",
                                    state: "Santa Pola",
                                    space: 60,
                                    room: 2, 
                                    lavatory: 1,
                                    terraza:"si",
                                    balcon: "no",
                                    floor: "Bajo",
                                    comOne:"exterior sin ascensor",
                                    dopCom:"Garaje incluido",
                                    location: "Orientación oeste",
                                    constr: 1991, 
                                    text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece bonito apartamento en planta baja, ubicado en la zona de la playa del Tamarit, (urbanización Paraíso), 60 metros construidos según catastro. Descripción: La vivienda dispone de dos dormitorios con armarios empotrados, un baño completo, cocina independiente con galería/lavadero, y salón comedor con aire acondicionado, y acceso a la terraza. Ubicada en una urbanización muy bien cuidada y con pocos gatos de comunidad, con parque de juegos infantil, zona de aparcamiento, piscina comunitaria y pista de tenis. El apartamento esta situado en una zona con servicios cerca y a pasos del pueblo, por lo que también es ideal como vivienda habitual o para vacacionar. Es una gran oportunidad que no deberías dejar escapar...",
                                    foto: "https://cdn.glitch.global/5539ba06-aed1-42cf-9a61-66f8d214a4d8/2022-10-17%20(3).png?v=1666006179548",
                                    showMore: false,  
                                    precio:95000, },
                                    {
                                        id:9,
                                        name:"Piso en venta en calle Mayor",
                                        zona:"Centro",
                                        tipo:"Apartamentos",
                                        state: "Santa Pola",
                                        space: 117,
                                        room: 3, 
                                        lavatory: 2,
                                        terraza:"no",
                                        balcon: "no",
                                        floor: "Bajo",
                                        comOne:"exterior sin ascensor",
                                        dopCom:"Garaje - no",
                                        location: "Orientación sur",
                                        constr: 1970, 
                                        text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece planta baja en la zona centro de Santa Pola. La vivienda es totalmente exterior, muy luminosa 117 metros construidos según catastro. Se compone de: - 3 Dormitorios amplios - 1 Baño completo y 1 aseo - Cocina independiente - 2 patios interiores - salón comedor. Ubicado en la zona centro de Santa Pola, rodeado de todo tipo de servicios y a pocos metros de la playa...",
                                        foto: "https://cdn.glitch.global/5539ba06-aed1-42cf-9a61-66f8d214a4d8/2022-10-17%20(6).png?v=1666013254753",
                                        showMore: false,  
                                        precio:90000, },
                                        {
                                            id:10,
                                            name:"Piso en venta en pasaje GRANADA",
                                            state: "Santa Pola",
                                            zona:"Puerto",
                                            tipo:"Apartamentos",
                                            space: 80,
                                            room: 3, 
                                            lavatory: 1,
                                            terraza:"no",
                                            balcon: "si",
                                            floor: "Planta 2ª",
                                            comOne:"exterior con ascensor",
                                            dopCom:"Garaje - no",
                                            location: "Orientación sur",
                                            constr: 1978, 
                                            text: "ROSA ROCAMORA Servicios Inmobiliarios les ofrece en pleno centro de Santa Pola, rodeado de todo tipo de servicios y a pasos del Paseo Marítimo; encontramos este piso en segunda planta con ascensor. Piso en muy buenas condiciones que cuenta con 80 m² construidos según catastro distribuidos en 3 habitaciones, 1 baño, cocina abierta al salón. A pocos kilómetros del aeropuerto, así como las ciudades de Elche y Alicante. ",
                                            foto: "https://cdn.glitch.global/5539ba06-aed1-42cf-9a61-66f8d214a4d8/2022-10-17%20(7).png?v=1666013878084",
                                            showMore: false, 
                                            precio:125000,  },
    ]